### ISSUE TITLE
joshuaulrich/quantmod裝不起來

### ISSUE THREAD

**Issue by KuiMing** [datasci-info/BeATradeR#11]

**Comment by lovelybigdata** [comment]
我發現
(1)在 linux 中可以直接這樣裝  : install_github("joshuaulrich/quantmod")

Package: quantmod
Type: Package
Title: Quantitative Financial Modelling Framework
Version: 0.4-5
Date: 2015-07-23

(2)在 mac 或是 windows 中這樣裝 : install.packages( "quantmod" )
Package: quantmod
Type: Package
Title: Quantitative Financial Modelling Framework
Version: 0.4-5
Date: 2015-07-23

其實版號是一樣的…
BugReports: https://github.com/joshuaulrich/quantmod/issues
看來後續都是由 joshuaulrich 進行維護了

**Comment by KuiMing** [comment]
感謝提醒，剛剛檢查了一下，果然最後更新日期都是2015.07.24，且之前OANDA的問題也解決了，感謝佳宏。
